source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

# ignore all warnings from all pods
inhibit_all_warnings!

#pod 'JSQSystemSoundPlayer', '~> 2.0’

pod 'XLForm', '~> 3.0'
pod 'iOS7Colors', '~> 2.0.0'
#pod 'GPUImage'
pod 'FXBlurView'  			# realtime blur view of background 
pod 'FXLabel'
pod 'CMPopTipView'
pod 'AMPopTip'
pod 'FlatUIKit'
pod 'AFNetworking', '~> 2.6.3'
pod 'RDVTabBarController'
pod 'SDWebImage','~>3.7.4'
#pod 'RDVKeyboardAvoiding'
pod 'JGActionSheet'

pod 'BlocksKit'


pod 'MGSwipeTableCell'
#pod 'DZNPhotoPickerController'

pod 'RBBAnimation', '0.4.0'

pod 'Shimmer'

pod 'Masonry', '0.5.3'

#pod 'TTTAttributedLabel', '1.10.1'

pod 'RegexKitLite-NoWarning', '1.1.0'

pod 'UIImage+BlurredFrame', '0.0.4'
pod 'FDFullscreenPopGesture', '1.1'

pod 'MBProgressHUD'

pod 'MWPhotoBrowser'

pod 'MJRefresh'
pod 'YTKKeyValueStore'

pod 'JTCalendar', '~> 2.0'

pod 'FLAnimatedImage', '~> 1.0'
